os:
  - osx
env:
  global:
  - VERSION="0.7.1.post6"
install:
  - brew update; brew install python3
  - git clone -b ${VERSION} git://github.com/igraph/python-igraph
  - cd python-igraph
  - python -m pip install -U pip wheel delocate
  - python -m pip wheel .
  - python3 -m pip install -U pip wheel delocate
  - python3 -m pip wheel .
  - delocate-wheel ./*.whl
script:
  - pwd
  - ls
